const typography = {
  fontSizes: {
    // MS: Desktop typography from Alceo Design System
    "w-hero": "56px",
    "w-h1": "48px",
    "w-h2": "36px",
    "w-h3": "28px",
    "w-h4": "24px",
    "w-h5": "20px",
    "w-h6": "16px",
    "w-lead-1l": "20px",
    "w-lead-2": "16px",
    "w-title-l": "14px",
    "w-subtitle-l": "14px",
    "w-body-1l": "16px",
    "w-body-2l": "14px",
    "w-small-l": "12px",
    "w-small-2l": "10px",

    // MS: Mobile typography from Alceo Design System
    "m-hero": "42px",
    "m-h1": "32px",
    "m-h2": "28px",
    "m-h3": "24px",
    "m-h4": "20px",
    "m-h5": "16px",
    "m-h6": "14px",
    "m-lead-1l": "16px",
    "m-lead-2": "14px",
    "m-title-l": "12px",
    "m-subtitle-l": "12px",
    "m-body-1l": "14px",
    "m-body-2l": "12px",
    "m-small-l": "10px",
    "m-small-2l": "8px",
  },
  lineHeights: {
    // MS: Desktop typography from Alceo Design System
    "w-hero": "75px",
    "w-h1": "74px",
    "w-h2": "56px",
    "w-h3": "42px",
    "w-h4": "36px",
    "w-h5": "30px",
    "w-h6": "24px",
    "w-lead-1l": "30px",
    "w-lead-2": "24px",
    "w-title-l": "22px",
    "w-subtitle-l": "22px",
    "w-body-1l": "26px",
    "w-body-2l": "22px",
    "w-small-l": "20px",
    "w-small-2l": "16px",

    // MS: Mobile typography from Alceo Design System
    "m-hero": "63px",
    "m-h1": "46px",
    "m-h2": "36px",
    "m-h3": "30px",
    "m-h4": "25px",
    "m-h5": "24px",
    "m-h6": "24px",
    "m-lead-1l": "24px",
    "m-lead-2": "21px",
    "m-title-l": "18px",
    "m-subtitle-l": "18px",
    "m-body-1l": "21px",
    "m-body-2l": "18px",
    "m-small-l": "15px",
    "m-small-2l": "12px",
  },
  fontWeights: {
    hairline: 100,
    thin: 200,
    light: 300,
    normal: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
    black: 900,
  },
  fonts: {
    heading: `"Maax", sans-serif`,
    body: `"Maax", sans-serif`,
  },
};

export default typography;
